spring.application.name=demo
server.port=${PORT:8080}
# ================= DATABASE CONFIG =================
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=LMS_DB;encrypt=true;trustServerCertificate=true;
spring.datasource.username=lms_user
spring.datasource.password=Password123!




spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

# Optional: HikariCP settings (default connection pool)
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.connection-timeout=30000

# Hibernate / JPA (if you use it)
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp
