spring.application.name=demo
server.port=${PORT:8080}
# ================= DATABASE CONFIG =================

spring.datasource.url=jdbc:postgresql://leaveapplication_user:DzThngtISbu3WsxICu1ZFkr4F0lhLE30@dpg-d6jfc5ua2pns739c74k0-a.virginia-postgres.render.com/leaveapplication

spring.datasource.username=leaveapplication_user

spring.datasource.password=DzThngtISbu3WsxICu1ZFkr4F0lhLE30
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Optional: HikariCP settings (default connection pool)
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.connection-timeout=30000



spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp